### ISSUE TITLE
Missing `service.js` file

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client-plugin-base-template#1]
Remember to add the implementation of that file:

https://github.com/g3w-suite/g3w-client-plugin-base-template/blob/2a488e9174f08eecd4c78874955590336847f98a/index.js#L2

**Comment by volterra79** [comment]
@Raruto fix https://github.com/g3w-suite/g3w-client-plugin-base-template/commit/e842709e1ac24f641510266a5f80205119851837
