### ISSUE TITLE
Explain better or avoid the using of `load()` as function alias

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client-plugin-base-template#3]
Better to avoid the use of aliases if not strictly necessary:

https://github.com/g3w-suite/g3w-client-plugin-base-template/blob/e842709e1ac24f641510266a5f80205119851837/index.js#L29-L31

https://github.com/g3w-suite/g3w-client-plugin-base-template/blob/e842709e1ac24f641510266a5f80205119851837/index.js#L11-L27

**Comment by volterra79** [comment]
@Raruto fix https://github.com/g3w-suite/g3w-client-plugin-base-template/commit/3ea25a37918bf112e2d8f422b94a653264508dac
